FROM node:24-bookworm-slim

WORKDIR /app


RUN apt-get update \
    && apt-get install -y \
       python3 \
       python3-pip \
    && rm -rf /var/lib/apt/lists/*


COPY package*.json ./

RUN npm install --omit=dev


COPY requirements.txt ./

RUN pip3 install \
    --no-cache-dir \
    --break-system-packages \
    -r requirements.txt


COPY server.js ./

COPY ai ./ai

COPY public ./public


ENV NODE_ENV=production
ENV PORT=8000


EXPOSE 8000


CMD ["node", "server.js"]